# syntax=docker/dockerfile:1

FROM python:3.9-slim-buster

ENV PYTHONPATH "${PYTHONPATH}:."

WORKDIR /app
COPY requirements-api.txt .
RUN pip3 install -r requirements-api.txt

COPY . .

EXPOSE 5000
CMD python3 webapps/api/app.py
