# syntax=docker/dockerfile:1

FROM python:3.11-slim-bullseye

ENV PYTHONPATH "${PYTHONPATH}:."

WORKDIR /app

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y gcc default-libmysqlclient-dev pkg-config \
    && rm -rf /var/lib/apt/lists/*
COPY requirements-frontend.txt .    
RUN pip3 install -r requirements-frontend.txt

COPY . .

EXPOSE 8000
CMD python3 webapps/frontend/app.py
