def average_power(energy, duration):
    """Average power to produce an input amount of energy over an input duration of time"""
    return energy / duration if duration > 0 else 0.0

def energy(power, duration):
    """Energy generated by an input supply of power over an input duration of time"""
    return power * duration
